name: CD
on:
  push:
    tags:
      - v*

jobs:
  build:
    permissions:
      contents: read
      packages: read
    name: Build
    uses: ./.github/workflows/test.yaml

  deploy:
    environment: production
    permissions:
      contents: write
      packages: write
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: lib-artifact-${{ github.sha }}
      - name: Publish Artifact to NPM Registry
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GH Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
