name: CD
on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/test.yaml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          registry-url: https://npm.pkg.github.com/
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: lib-dist-artifact-${{ github.sha }}
          path: dist
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GH Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
