name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  packages: read

jobs:
  test:
    uses: ./.github/workflows/test.yaml
