name: Main CI
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/test.yaml

  trigger-release:
    name: Next Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Print next version
        run: echo ${{ needs.build.outputs.version }}
