name: Main CI
on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: read
    name: Build
    uses: ./.github/workflows/test.yaml

  trigger-release:
    permissions:
      contents: write
    name: Next Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Set Package Version
        run: |
          npm version ${{ needs.build.outputs.version }} --no-git-tag-version --allow-same-version
      - uses: stefanzweifel/git-auto-commit-action@v6
        id: commit
        with:
          commit_message: "chore(version): Bump version to ${{ needs.build.outputs.version }}"
      - name: Create Tag (if version changed)
        if: steps.commit.outputs.changes_detected == 'true'
        run: |
          git tag v${{ needs.build.outputs.version }}
          git push origin v${{ needs.build.outputs.version }}
