name: Test
on:
  workflow_call:
    outputs:
      version:
        description: "The next version to be released"
        value: ${{ jobs.version.outputs.next }}

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Formating
        run: npm run format:check
      - name: Build dist
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib-artifact-${{ github.sha }}
          path: |
            lib
            .npmrc
            .nvmrc
            package.json
          if-no-files-found: error

  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      next: ${{ steps.next.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Include tags so that the version can be determined
          fetch-depth: 0
      - name: Setup Conventional Versioning
        uses: jontze/.workflows/setup-conventional-versioning@main
        with:
          version: v0.2.2
      - name: Specify next version
        id: next
        run: |
          echo "version=$(conventional-versioning -o plain)" >> $GITHUB_OUTPUT
